### ISSUE TITLE
Support gpt4 

### ISSUE THREAD

**Issue by telegreen** [gaomar/node-red-contrib-simple-chatgpt#3]
" When msg.topic is set to gpt4:
  [Required] msg.payload should be a well-written prompt that provides enough information for the model to know what you want 
  and how it should respond. Its success generally depends on the complexity of the task and quality of your prompt."  

When I set in node msg.topic to "gpt4" and make request :

{"message":"The model: `gpt-4` does not exist",
  "type":"invalid_request_error",
   "param":null,"
    code":"model_not_found"}

So GPT-4 model is not supported?

**Comment by HaroldPetersInskipp** [comment]
If you receive "The model: gpt-4 does not exist" then you probably do not have access to that model. You can use the following script to check what models are available to a specific API KEY:

```javascript
const { Configuration, OpenAIApi } = require("openai");

async function listModels() {
    const configuration = new Configuration({
      apiKey: "YOUR KEY HERE",
    });
    const openai = new OpenAIApi(configuration);
    const response = await openai.listModels();
    console.log(response.data.data);
}

listModels();
```
